name: flutter_assignment
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.7.1
  collection: ^1.17.1
  connectivity_wrapper: ^1.1.3
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  dynamic_color: ^1.6.5
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.2
  intl: ^0.18.1
  material_color_utilities: ^0.2.0
  material_theme_builder: ^1.0.4
  parallax: ^1.0.3
  provider: ^6.0.5
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/light/
    - assets/images/dark/
    - assets/images/shared/
