// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns the [FirebaseOptions] for the current platform.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return _web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      case TargetPlatform.macOS:
        return _macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions _web = FirebaseOptions(
    apiKey: 'AIzaSyDc1KRpsYuWZDgWXwOuNQRxw4HO1hgFjCY',
    appId: '1:963693634804:web:3a19372aeeca7edcd5aaa1',
    messagingSenderId: '963693634804',
    projectId: 'flutter-assignment-elred',
    authDomain: 'flutter-assignment-elred.firebaseapp.com',
    storageBucket: 'flutter-assignment-elred.appspot.com',
  );

  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: 'AIzaSyCbWr3MxUug5UyPRUlLze3Exk-o3ODVetc',
    appId: '1:963693634804:android:3bc5fc5c90f4fe35d5aaa1',
    messagingSenderId: '963693634804',
    projectId: 'flutter-assignment-elred',
    storageBucket: 'flutter-assignment-elred.appspot.com',
  );

  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: 'AIzaSyCPT9Jtms6AY8ICo-und1Nc3g7vIrqBKE0',
    appId: '1:963693634804:ios:146b35a70ffa6613d5aaa1',
    messagingSenderId: '963693634804',
    projectId: 'flutter-assignment-elred',
    storageBucket: 'flutter-assignment-elred.appspot.com',
    iosClientId:
        '963693634804-6uga4eplkltj4rev1n7isng6fbnm519h.apps.googleusercontent.com',
    iosBundleId: 'com.elred.flutterAssignment',
  );

  static const FirebaseOptions _macos = FirebaseOptions(
    apiKey: 'AIzaSyCPT9Jtms6AY8ICo-und1Nc3g7vIrqBKE0',
    appId: '1:963693634804:ios:e234340839e1a1e0d5aaa1',
    messagingSenderId: '963693634804',
    projectId: 'flutter-assignment-elred',
    storageBucket: 'flutter-assignment-elred.appspot.com',
    iosClientId:
        '963693634804-s5pfte2of3vskk3funjfua5hnumpafmv.apps.googleusercontent.com',
    iosBundleId: 'com.elred.flutterAssignment.RunnerTests',
  );
}
